teacher_path: "models/layer1_index0/teacher.pt"
autoencoder_path: "models/layer1_index0/autoencoder.pt"
student_path: "models/layer1_index0/student.pt"
quantiles_path: "models/layer1_index0/quantiles.pt"

# pdn divides input size by 4
out_resolution:
  width: 64 #128
  height: 64 #72

out_channels:
  teacher: 256
  autoencoder: 256